env: "local"
log_level: "debug" 

http_server:
  address: "localhost:8080"
  server_port: "8080"
  timeout: 5s
  idle_timeout: 1m

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: subscriptions
  sslmode: disable
  migrations_path: "./internal/storage/migrations"